name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: dotnet Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet publish -c Release -o publish --no-restore
    - name: Upload artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: webapp
        # Directory containing files to upload
        path: publish
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: webapp
      # set up az cli login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # deploy web app using Azure credentials
      - name: 'Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'actions-demo-app'
          package: 'webapp'
      
